### ISSUE TITLE
Updating from 3.9.5 to 3.9.6 breaks global styles

### ISSUE THREAD

**Issue by mlbiche** [sveltejs/svelte-preprocess#175]
**Describe the bug**
When updating from 3.9.5 to 3.9.6, global styles are broken.

Here is my svelte.config.js file :

```js
const { scss, globalStyle } = require('svelte-preprocess')

module.exports = (production) => ({
  // enable run-time checks when not in production
  dev: !production,
  // we'll extract any component CSS out into
  // a separate file - better for performance
  css: css => {
    css.write('public/build/bundle.css')
  },
  preprocess: [
    scss({
      includePaths: [
        './src/styles',
        './node_modules'
      ]
    }),
    globalStyle()
  ]
})
```

I have `sass@1.26.8` and `postcss@7.0.32` installed. Updating `scss` config to include `implementation: require('sass')` does not fix the issue.

When checking the bundle.css file, all the global style is missing, while it exists in the bundle.map.css file 🤔 

My global styles just concern the following :

In my Svelte component :
```html
...

<style src="App.scss" global></style>
```

In App.scss file :

```scss
@use "@material/theme";
@use "@material/typography/mdc-typography";
@use "@material/button/mdc-button";
@use "@material/icon-button/mdc-icon-button";
@use "@material/textfield/mdc-text-field";
@use "@material/drawer/mdc-drawer";
@use "@material/list/mdc-list";
@use "@material/chips/mdc-chips";
@use "@material/menu-surface/mdc-menu-surface";
@use "@material/menu/mdc-menu";
@use "@material/select/mdc-select";
@use "@material/card/mdc-card";
@use "@material/top-app-bar/mdc-top-app-bar";
@use "@material/fab/mdc-fab";
@use "@material/linear-progress/mdc-linear-progress";
@use "@material/dialog/mdc-dialog";
@use "@material/form-field/mdc-form-field";
@use "@material/checkbox/mdc-checkbox";
@use "@material/snackbar/mdc-snackbar";
@use "@material/textfield/helper-text/mdc-text-field-helper-text";

main {
  padding: 124px 8px 32px 8px;
  margin: 0 auto;
  min-height: calc(100vh - 156px);
  display: flex;
  align-items: center;
  max-width: 400px;

  > * {
    width: 100%;
  }
}
```

Not only all the Material style is missing but the `main` rule too.

**Expected behavior**

Having a working global style 😬 

**Information about your project:**

- Your browser and the version: Firefox 77.0.1, Brave 1.9.76

- Your operating system: OS X 10.15.5

- `svelte-preprocess` version: 3.9.6 (the bug is not present in 3.9.5)

- Whether your project uses Webpack or Rollup: Rollup
