### ISSUE TITLE
Not globalizing nth-child correctly

### ISSUE THREAD

**Issue by Skayo** [sveltejs/svelte-preprocess#224]
**Describe the bug**
This global style:
```html
<style global>
  .uk-subnav-divider > :nth-child(n+2):not(.uk-first-column)::before {
    border-left-color: #e5e5e5;
  }
</style>
```

Gets processed into to this:
```css
:global(.uk-subnav-divider) > :global(:nth-child(n)+:global(2):not(.uk-first-column)::before) {
  border-left-color: #e5e5e5;
}
```

Which makes the rule unusable.

**Expected behavior**
```css
:global(.uk-subnav-divider) > :global(:nth-child(n+2):not(.uk-first-column)::before) {
  border-left-color: #e5e5e5;
}
```

I'd recommend you to add all these to the tests:
[:nth-child() - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)

**Information about your project:**

- Chrome 84.0.4147.125
- Windows 10
- `svelte-preprocess` version: 4.0.12
  - Set `implementation` option to `sass`, version 1.26.10
- Rollup

**Additional context**
Actually what I'm trying to do is importing UIKit 3 inside a component:
```html
<style global lang="scss">
  @import "uikit/src/scss/mixins-theme";
  @import "uikit/src/scss/variables-theme";
  @import "uikit/src/scss/uikit-theme";
</style>
```
