### ISSUE TITLE
[SCSS] @use creates duplicate styles when used in different svelte files linking the same scss file.

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/svelte-preprocess#243]
### Describe the bug
When I import files with [`@use`](https://sass-lang.com/documentation/at-rules/use), they should be imported only *once* when I have included them in *one or more* files.

### To Reproduce

**File1.svelte**
```html
<style lang="scss" global>
  @use "./some_other_styles.scss";
  @use "./global.scss";
</style>
```

**File2.svelte**
```html
<style lang="scss" global>
  @use "./global.scss";
</style>
```

**global.scss**
```scss
p {color: red;}
```

**Output**
```scss
p {color: red;} 
p {color: red;}
```

**Expected behavior**
```scss
p {color: red}
```

**Information about your project:**
- Your operating system: Windows 10
- `svelte-preprocess` version 4.2.1
- Rollup
