### ISSUE TITLE
prependData; Svelte ignores CSS rules for generic HTML elements made inside the prepended File

### ISSUE THREAD

**Issue by Sensanaty** [sveltejs/svelte-preprocess#248]
**Describe the bug**
When using the `scss: { prependData }` option, CSS definitions for generic HTML elements will be ignored

```scss
// global.scss
body { background: pink }
```

The `bundle.css` file generated is empty.

The `body` rule will never be applied anywhere. If I instead declare a specific class rule, however, the rule will get applied

```scss
// global.scss
.className { background: pink }
```

The `bundle.css` file generated has the definition

```css
.className.svelte-1c0bzmr{background:pink}
```

My `rollup.config`

```javascript
import preprocess from "svelte-preprocess";

export default {
  plugins: [
    svelte({
      preprocess: preprocess({
        scss: {
	  prependData: `@import './src/assets/styles/global.scss';`
	}
      })
    })
}
```

**Logs**
Both the CLI console and the browser console show no errors

**To Reproduce**
- Initialize a fresh repo using `npx degit sveltejs/template`.
- Add `svelte-preprocess` and `node-sass` as deps
- Create the file `src/assets/styles/global.scss` and setup `prependData` as I did above in my `rollup.config.js`
- Add a generic HTML element rule, like `body { background: pink }`

**Expected behavior**
The rules inside of the `global.scss` should take effect regardless of whether I target a specific CSS selector or if I only target an HTML element

**Information about your project:**

- Your browser and the version: Chrome 85.0.4183.102 (Official Build) (64-bit)

- Your operating system: Ubuntu 20.04.01 LTS

- `svelte-preprocess` version: `4.2.1`

-  Rollup

**Additional context**
I'm new to Svelte, so I assume that this issue stems from the way Svelte by default shakes out unused CSS definitions, however I don't see how that can be applicable for something like a generic HTML element selector

**Comment by Sensanaty** [comment]
Simple fix, I just had to add the magic `:global()` pseudoselector.

```scss
// global.scss
:global(body) { background: pink }
```
