### ISSUE TITLE
Nested selectors with pseudo-elements, where the parent is inside a :global(), compiles to broken CSS

### ISSUE THREAD

**Issue by Karl255** [sveltejs/svelte-preprocess#384]
**Describe the bug**
I have this SCSS code inside a component:
```scss
.dropdown {
	> :global(a) {
		color: black;
		
		&:hover {
			color: tomato;
		}
		
		&:first-child {
			color: seagreen;
		}
		
		&::after {
			content: "abc";
		}
	}
}
```
And it compiles to:
```css
.dropdown.svelte-1aq84zf > a { /* compiles correctly */
	color: #000;
}
.dropdown.svelte-1aq84zf > a:hover { /* compiles correctly */
	color: tomato;
}
.dropdown.svelte-1aq84zf > a:first-child { /* compiles correctly */
	color: #2e8b57;
}
.dropdown.svelte-1aq84zf > .svelte-1aq84zfa::after { /* broken selector */
	content: "abc";
}
/*                         ^^^^^^^^^^^^^^^! */
```
There's 2 issues with this:
1. The class selector marked with `^^^` should not be there
2. The class selector also merges with the `a` selector (marked with `!`), meaning the select won't match with anything ever. I think the issue here is the order of which selector is added first by the precompiler.

The expected behavior would be the marked class selector not appearing in the compiled CSS and especially have it not merge with the `a`.

**Logs**
Compiles/builds without errors or warnings.

**To Reproduce**
A minimal SvelteKit project to reproduce this: [https://github.com/Karl255/sveltekit-bug-demo](https://github.com/Karl255/sveltekit-bug-demo)

**Information about your project:**
- Operating system: Ubuntu 20.04 on WSL on Windows 10 version 21H1 (build 19043.1083)
- `svelte-preprocess` version: 4.7.4 (also tested with 4.7.3 where the bug appears too)
- Project uses SvelteKit
