### ISSUE TITLE
ValidationError: :global(whith-selector) can't be in the middle

### ISSUE THREAD

**Issue by Valexr** [sveltejs/svelte-preprocess#419]
```scss
// forms.scss

.form-input-hint { // <- root class
  .has-success & { // <- it's reverse to parent
    color: $success-color;
  }
}
```

```sv
// component

<style lang="scss">
  :global(.spectre) { // <- current level scope with selector inside
    @import 'spectre.css/src/forms';
  }
</style>
```

```css
/* output */

/* [parent] ---- [scope] --------- [class] */
.has-success :global(.spectre) .form-input-hint {
  color: #32b643;
}
```

it’s just svelte compilation error

```sh
ValidationError: :global(...) can be at the start or end of a selector sequence, but not in the middle
```
But if don't use selector inside `:global` it's compiled ok without errors:

```sv
// component

<style lang="scss">
  :global { // <- current level scope without selector inside
    @import 'spectre.css/src/forms';
  }
</style>
```

```css
/* output */

/* [parent] - [scope] --- [class] */
.has-success :global .form-input-hint {
  color: #32b643;
}
```
