### ISSUE TITLE
unexpected style when I use `:where` in global CSS

### ISSUE THREAD

**Issue by saadeghi** [sveltejs/svelte-preprocess#425]
**Describe the bug**
When I add a PostCSS preprocessor to svletekit, below CSS code doesn't work anymore:
```
<style global>
.btn:where(.btn-primary,.btn-secondary){
  background-color: green;
}
</style>
```

**To Reproduce**
1. Clone this: https://github.com/saadeghi/svelte-preprocess-postcss-bug
1. `npm install`
1. `npm run dev`
1. now uncomment [line 5 on svelte.config.js](https://github.com/saadeghi/svelte-preprocess-postcss-bug/blob/583e35efe134baa6184932b9d85a22691721f1d1/svelte.config.js#L5) to disable the preprocess and `npm run dev` again to see expected style

**Expected behavior**

Expected CSS:
```css
.btn:where(.btn-primary,.btn-secondary){
  background-color: green;
}
```
generated CSS:
```css
.btn:where(.btn-primary),:global(.btn-secondary){
  background-color:green
}
```

**Information about your project:**
https://github.com/saadeghi/svelte-preprocess-postcss-bug
